/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IdentityProviderKind = "github" | "google" | "microsoft";

export type SkillInstallSource = "cli" | "mcp" | "web";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "reader" | "superadmin" | "writer";

export interface Accounts {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Connections {
  access_token: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp | null;
  external_account_id: string;
  external_account_login: string;
  id: Generated<string>;
  integration_id: string;
  provider: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface IdentityProviders {
  client_id: string;
  client_secret: string;
  created_at: Generated<Timestamp>;
  display_name: string;
  enabled: Generated<boolean>;
  id: Generated<string>;
  kind: IdentityProviderKind;
  permitted_organisations: Generated<string[]>;
  updated_at: Generated<Timestamp>;
}

export interface Integrations {
  app_slug: string | null;
  client_id: string;
  client_secret: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  display_name: string;
  id: Generated<string>;
  provider: string;
  updated_at: Generated<Timestamp>;
}

export interface RateLimits {
  count: number;
  id: Generated<string>;
  key: string;
  last_request: number;
}

export interface ResourceAnalytics {
  install_count: number;
  resource_id: string;
}

export interface ResourceDirectory {
  allowed_tools: string | null;
  description: string;
  id: string;
  install_count: number;
  kind: string;
  name: string;
  namespace: string;
  published_by_name: string;
  search: string | null;
  source: string | null;
  tags: Array<{ id: string; name: string }>;
  updated_at: Date;
}

export interface ResourceInstallEvents {
  client_fingerprint: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  resource_id: string;
  source: SkillInstallSource;
}

export interface Resources {
  body: string | null;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  kind: string;
  name: string;
  namespace: string;
  payload: Record<string, unknown>;
  published_at: Generated<Timestamp>;
  published_by: string | null;
  published_by_email: string;
  published_by_name: string;
  search: Generated<string | null>;
  source: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ResourceSubmissions {
  body: string | null;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  kind: string;
  name: string;
  namespace: string;
  payload: Record<string, unknown>;
  source: string;
  submitted_by: string | null;
  submitted_by_email: string;
  submitted_by_name: string;
  updated_at: Generated<Timestamp>;
}

export interface ResourceTags {
  created_at: Generated<Timestamp>;
  resource_id: string;
  tag_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface Tags {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface Tokens {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  name: string;
  token_hash: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  first_name: string;
  id: Generated<string>;
  image: string | null;
  last_name: string;
  must_change_password: Generated<boolean>;
  name: Generated<string>;
  role: UserRole;
  updated_at: Generated<Timestamp>;
}

export interface Verifications {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface DB {
  accounts: Accounts;
  connections: Connections;
  identity_providers: IdentityProviders;
  integrations: Integrations;
  rate_limits: RateLimits;
  resource_analytics: ResourceAnalytics;
  resource_directory: ResourceDirectory;
  resource_install_events: ResourceInstallEvents;
  resource_submissions: ResourceSubmissions;
  resource_tags: ResourceTags;
  resources: Resources;
  sessions: Sessions;
  tags: Tags;
  tokens: Tokens;
  users: Users;
  verifications: Verifications;
}
