import { sql } from "drizzle-orm";
import { boolean, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

// Column names and TS property keys are both snake_case, matching the wire
// (docs/openapi.json) 1:1 — there is no separate camelCase domain shape to
// convert to or from. The Better Auth columns below are generated by
// `@better-auth/cli generate` (see src/db/schemas/README.md) and then mapped
// back to that convention in `auth/instance.ts`.

export const userRoleEnum = pgEnum("user_role", ["reader", "writer", "admin", "superadmin"]);

export const users = pgTable(
  "users",
  {
    // Postgres 18's native uuidv7() (this repo runs postgres:18-alpine) —
    // time-ordered, so an id sorts the same as its row's creation order,
    // unlike the random v4 gen_random_uuid() this replaced. The CLI emits a
    // `text` id because Better Auth normally generates one itself; here
    // `generateId: false` hands that job to Postgres.
    id: uuid("id").primaryKey().default(sql`uuidv7()`),
    email: text("email").notNull().unique(),
    first_name: text("first_name").notNull(),
    last_name: text("last_name").notNull(),
    // Better Auth reads one display name where this Registry stores two halves
    // (docs/data-model.md). Generated rather than written, so a rename through
    // `updateOwnName` cannot leave the two out of step — there is no write path
    // to keep in sync because there is no write path at all. Better Auth never
    // assigns it: Users are created by /setup, by an Admin, or by an external
    // login, never by its sign-up endpoint (which is disabled, ADR-0016).
    name: text("name")
      .notNull()
      .generatedAlwaysAs(sql`first_name || ' ' || last_name`),
    // Better Auth's own flag, and a required field on its user model. The
    // Registry does not verify addresses itself: a password User is created by
    // someone who already knows the address, and an external login is only
    // admitted when the Provider asserts the address is verified (ADR-0015).
    email_verified: boolean("email_verified").notNull().default(false),
    // Required by Better Auth's user model and unused here — the interface
    // shows initials, not avatars.
    image: text("image"),
    // Declared to Better Auth as `additionalFields`, which is why the CLI emits
    // both as nullable text. Neither is optional in this Registry: a User
    // always has a role (ADR-0015), so both keep the stricter column.
    role: userRoleEnum("role").notNull(),
    must_change_password: boolean("must_change_password").notNull().default(false),
    created_at: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updated_at: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    // At most one superadmin, ever — set once at /setup and never
    // reassigned. The database enforces the cardinality; the application
    // enforces that it's never granted, changed, or removed afterwards.
    uniqueIndex("users_role_superadmin_index").on(table.role).where(sql`${table.role} = 'superadmin'`),
  ],
);

export type UserRow = typeof users.$inferSelect;
export type NewUserRow = typeof users.$inferInsert;
